export default {
  // Auth Screen
  WELCOME1: 'GetStart',
  WELCOME2: 'GetStart2',
  LOGIN1: 'Login1',
  LOGIN2: 'Login2',
  SIGNUP: 'SignUp',
  MESSAGES: 'MessageScreen',
  CHAT_MESSAGS: 'MessItem',
  SEARCH: 'SearchScreen',
  PRODUCT: 'Product',
  ADD_PRODUCT: 'AddProduct',
  UPDATE_PRODUCT: 'UpdateProduct',

  ORDER_HISTORY: 'OrderHistory',
  SHOP: 'ShopScreen',
  SHOP_UPDATE: 'ShopUpdate',
  PROMOTION: 'PromotionScreen',
  STATIS: 'StatisticalScreen',
  INVENTORY: 'InventoryScreen',
  NGANH_SP: 'Nganhsp',
  NGANH_SPUPDATE: 'NganhspUPDATE',
  PHAN_LOAI_SP: 'Phanloaisp',
  PHAN_LOAI_SPUPDATE: 'PhanloaispUPDATE',
  DISCOUNT: 'Discount',
  DISCOUNT_ITEM: 'DiscountItem',
  DISCOUNT_ADD: 'AddDiscount',
  DISCOUNT_UPDATE: 'UpdateDiscount',
  PASSWORD: 'Password',
  SETTING: 'SettingScreen',
  CONTACT: 'ContactSup',
  NOTIFI: 'NotifiScreen',
  NOTIFI_ITEM: 'NotiItem',
  //Botton Tabs Screen
  TAB_ROUTER: 'BottomTab',
  HomeScreen: 'HomeScreen',
  ORDER: 'Order',
  PROFILE: 'Profile',
  ChitietProduct: 'ChitietProduct',
  OTPScreen: 'OTPScreen',
};
